"""Embeds og OoTMM's CSMC container art into the launcher as decoded RGBA arrays.

The launcher's native builder (src/launcher/ForeignModelMods.cpp) bakes the same og-parity CSMC
assets as tools/build_csmc_assets.py but must run on end-user machines with no Python/Pillow/OoTMM
checkout. This decodes the og PNGs (og's OWN art) at dev time into the COMMITTED
src/launcher/CsmcArtData.gen.cpp. Re-run whenever og's pots/chests/crates art changes:

    python tools/gen_csmc_art_embed.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OG_ASSETS = ROOT / "external/OoTMM/packages/generator/data/assets"
OUT = ROOT / "src/launcher/CsmcArtData.gen.cpp"
SUBDIRS = ("pots", "chests", "crates")


def main() -> None:
    arts = []
    for sub in SUBDIRS:
        for path in sorted((OG_ASSETS / sub).glob("*.png")):
            im = Image.open(path).convert("RGBA")
            arts.append((f"{sub}/{path.name}", im.size[0], im.size[1], im.tobytes()))

    lines = [
        "// GENERATED by tools/gen_csmc_art_embed.py from og OoTMM's",
        "// packages/generator/data/assets/{pots,chests,crates}/*.png (og's own art).",
        "// Do not edit; re-run the script when og's CSMC art changes.",
        "",
        "#include \"ForeignModelMods.hpp\"",
        "",
        "#include <cstring>",
        "",
        "namespace ootmm::launcher {",
        "namespace {",
    ]
    for i, (_rel, _w, _h, rgba) in enumerate(arts):
        rows = []
        for off in range(0, len(rgba), 24):
            rows.append(",".join(str(b) for b in rgba[off : off + 24]) + ",")
        lines.append(f"const unsigned char kArt{i}[] = {{")
        lines.extend(rows)
        lines.append("};")
    lines.append("const CsmcArt kCsmcArt[] = {")
    for i, (rel, w, h, _rgba) in enumerate(arts):
        lines.append(f'    {{ "{rel}", {w}, {h}, kArt{i} }},')
    lines.append("};")
    lines.append("} // namespace")
    lines.append("")
    lines.append("const CsmcArt* FindCsmcArt(const std::string& rel) {")
    lines.append("    for (const CsmcArt& art : kCsmcArt) {")
    lines.append("        if (rel == art.rel) {")
    lines.append("            return &art;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace ootmm::launcher")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUT}: {len(arts)} textures embedded")


if __name__ == "__main__":
    main()
