#!/usr/bin/env python3
"""Extract REAL game icons from the ports' o2r archives for the launcher GUI.

Reads LUS 'OTEX' texture resources (0x40-byte resource header, then
{u32 texType, u32 width, u32 height, u32 dataSize} at 0x40, pixel data at 0x50),
decodes them to RGBA8, and emits src/launcher/LauncherIcons.inc â€” embedded pixel
arrays the launcher uploads as D3D11 textures. No runtime zip/png dependencies.

texType: 1 = RGBA32 (R,G,B,A bytes), 2 = RGBA16 (5551 BE), 8 = IA8 (4-bit I, 4-bit A).

Run whenever the icon set changes. Also writes PNG previews to tools/icon_preview/.
"""

import struct
import zipfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OOT_O2R = ROOT / "external/Shipwright/x64/Debug/oot.o2r"
MM_O2R = ROOT / "external/2ship2harkinian/x64/Debug/mm.o2r"
OUT_INC = ROOT / "src/launcher/LauncherIcons.inc"
PREVIEW_DIR = ROOT / "tools/icon_preview"

# (C identifier, archive, entry path)
ICONS = [
    ("OcarinaOfTime", OOT_O2R, "textures/icon_item_static/gItemIconOcarinaOfTimeTex"),
    ("MasterSword", OOT_O2R, "textures/icon_item_static/gItemIconSwordMasterTex"),
    ("KokiriSword", OOT_O2R, "textures/icon_item_static/gItemIconSwordKokiriTex"),
    ("LensOfTruth", OOT_O2R, "textures/icon_item_static/gItemIconLensOfTruthTex"),
    ("DungeonMap", OOT_O2R, "textures/icon_item_24_static/gQuestIconDungeonMapTex"),
    ("Compass", OOT_O2R, "textures/icon_item_24_static/gQuestIconDungeonCompassTex"),
    ("BossKey", OOT_O2R, "textures/icon_item_24_static/gQuestIconDungeonBossKeyTex"),
    ("FierceDeityMask", MM_O2R, "icon_item_static_yar/gItemIconFierceDeityMaskTex"),
    ("BombersNotebook", MM_O2R, "icon_item_static_yar/gItemIconBombersNotebookTex"),
    ("MoonsTear", MM_O2R, "icon_item_static_yar/gItemIconMoonsTearTex"),
]


def decode_otex(blob):
    tex_type, width, height, data_size = struct.unpack_from("<4I", blob, 0x40)
    data = blob[0x50 : 0x50 + data_size]
    rgba = bytearray(width * height * 4)
    if tex_type == 1:  # RGBA32
        assert data_size == width * height * 4, "unexpected RGBA32 size"
        rgba[:] = data
    elif tex_type == 2:  # RGBA16 (5551, big-endian)
        assert data_size == width * height * 2
        for i in range(width * height):
            v = (data[i * 2] << 8) | data[i * 2 + 1]
            rgba[i * 4 + 0] = ((v >> 11) & 0x1F) * 255 // 31
            rgba[i * 4 + 1] = ((v >> 6) & 0x1F) * 255 // 31
            rgba[i * 4 + 2] = ((v >> 1) & 0x1F) * 255 // 31
            rgba[i * 4 + 3] = 255 if (v & 1) else 0
    elif tex_type == 8:  # IA8: 4-bit intensity, 4-bit alpha per byte
        assert data_size == width * height
        for i in range(width * height):
            b = data[i]
            intensity = (b >> 4) * 17
            alpha = (b & 0xF) * 17
            rgba[i * 4 + 0] = intensity
            rgba[i * 4 + 1] = intensity
            rgba[i * 4 + 2] = intensity
            rgba[i * 4 + 3] = alpha
    else:
        raise ValueError(f"unsupported texType {tex_type}")
    return width, height, bytes(rgba)


def write_png(path, width, height, rgba):
    def chunk(tag, payload):
        return (
            struct.pack(">I", len(payload))
            + tag
            + payload
            + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF)
        )

    raw = b"".join(b"\x00" + rgba[y * width * 4 : (y + 1) * width * 4] for y in range(height))
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )
    path.write_bytes(png)


def main():
    PREVIEW_DIR.mkdir(exist_ok=True)
    archives = {}
    entries = []
    for name, archive_path, entry in ICONS:
        if archive_path not in archives:
            archives[archive_path] = zipfile.ZipFile(archive_path)
        blob = archives[archive_path].read(entry)
        width, height, rgba = decode_otex(blob)
        entries.append((name, width, height, rgba))
        write_png(PREVIEW_DIR / f"{name}.png", width, height, rgba)
        print(f"{name}: {width}x{height} from {entry}")

    lines = [
        "// Generated by tools/gen_launcher_icons.py â€” REAL game icons decoded from the",
        "// ports' o2r archives (LUS OTEX resources). Do not edit by hand.",
        "",
    ]
    for name, width, height, rgba in entries:
        hex_bytes = ",".join(str(b) for b in rgba)
        lines.append(f"static const unsigned char kIconPixels{name}[] = {{ {hex_bytes} }};")
    lines.append("")
    lines.append("static const EmbeddedIcon kEmbeddedIcons[] = {")
    for name, width, height, rgba in entries:
        lines.append(f'    {{ "{name}", {width}, {height}, kIconPixels{name} }},')
    lines.append("};")
    lines.append("")
    OUT_INC.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_INC} ({len(entries)} icons)")


if __name__ == "__main__":
    main()
